plugins/loot/loot.so: plugins/loot/loot.c plugins/loot/loot.h plugins/game/game.h plugins/inventory/inventory.h
	cc -g -shared -fpic -o plugins/loot/loot.so plugins/loot/loot.c

PLUGINS := ${PLUGINS} plugins/loot/loot.so
