plugins/movement/movement.so: plugins/movement/movement.c plugins/movement/movement.h plugins/game/game.h
	cc -g -shared -fpic -o plugins/movement/movement.so plugins/movement/movement.c

PLUGINS := ${PLUGINS} plugins/movement/movement.so
