plugins/apple/apple.so: plugins/apple/apple.c plugins/game/game.h plugins/score/score.h
	cc -g -shared -fpic -o plugins/apple/apple.so plugins/apple/apple.c

PLUGINS := ${PLUGINS} plugins/apple/apple.so
