plugins/score/score.so: plugins/score/score.c plugins/score/score.h plugins/game/game.h
	cc -g -shared -fpic -o plugins/score/score.so plugins/score/score.c

PLUGINS := ${PLUGINS} plugins/score/score.so
