plugins/inventory/inventory.so: plugins/inventory/inventory.c plugins/inventory/inventory.h plugins/game/game.h
	cc -g -shared -fpic -o plugins/inventory/inventory.so plugins/inventory/inventory.c

PLUGINS := ${PLUGINS} plugins/inventory/inventory.so
