plugins/monster/monster.so: plugins/monster/monster.c plugins/game/game.h plugins/score/score.h
	cc -g -shared -fpic -o plugins/monster/monster.so plugins/monster/monster.c

PLUGINS := ${PLUGINS} plugins/monster/monster.so
