plugins/recharge/recharge.so: plugins/recharge/recharge.c plugins/recharge/recharge.h plugins/game/game.h
	cc -g -shared -fpic -o plugins/recharge/recharge.so plugins/recharge/recharge.c

PLUGINS := ${PLUGINS} plugins/recharge/recharge.so
