plugins/healthbar/healthbar.so: plugins/healthbar/healthbar.c plugins/game/game.h
	cc -g -shared -fpic -o plugins/healthbar/healthbar.so plugins/healthbar/healthbar.c

PLUGINS := ${PLUGINS} plugins/healthbar/healthbar.so
