plugins/bumblebee/bumblebee.so: plugins/bumblebee/bumblebee.c plugins/game/game.h
	cc -g -shared -fpic -o plugins/bumblebee/bumblebee.so plugins/bumblebee/bumblebee.c

PLUGINS := ${PLUGINS} plugins/bumblebee/bumblebee.so
